name: Test and Code Quality

on:
  push:
    branches: [ main, metrics-dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8
        pip install flask flask-cors
    
    - name: Initialize Database
      run: |
        mkdir -p db
        python -c "
        from db.database import init_db, insert_temperature
        from datetime import datetime, timedelta
        
        # Create empty database
        init_db()
        
        # Add test temperatures (like putting toy thermometers in the box)
        test_temps = [
            25.5,  # Normal temperature
            38.0,  # High temperature
            22.0,  # Low temperature
            30.0,  # Normal temperature
            35.5   # High-ish temperature
        ]
        
        # Insert each temperature
        for temp in test_temps:
            insert_temperature(temp)
        "
    
    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=api --cov-report=xml
    
    - name: Check code quality with flake8
      run: |
        flake8 api/ tests/ --max-line-length=100
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml